/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Excepciones.*;
import Modelo.UML.Centro;
import Modelo.UML.Localidad;
import Modelo.UML.Modelo;
import Modelo.UML.Municipio;
import Modelo.UML.Via;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import proyectoudaleku.Main;


public class PanInscripcion extends javax.swing.JPanel {
    private String prov;
    private boolean periodoIns;
    private boolean sorteo;
    
    ArrayList<Municipio> municipios;
    ArrayList<Localidad> localidades;
    ArrayList<Via> vias;
    ArrayList<Centro> centros;
    int munIndex;
    int locIndex;
    int viaIndex;
    int cenIndex;
    
    public PanInscripcion() {
        initComponents();
    }
    
    public PanInscripcion(String prov) {
    initComponents();
    this.prov=prov;
    datosIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        grupoProvincia = new javax.swing.ButtonGroup();
        grupoModelo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        pTutor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNombreTutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfApel1Tutor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfApel2Tutor = new javax.swing.JTextField();
        tfDniTutor = new javax.swing.JTextField();
        pMenor = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfNombreMenor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfApel1Menor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfApel2Menor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbMujer = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfDniMenor = new javax.swing.JTextField();
        tfFechaNacMenor = new javax.swing.JTextField();
        pDireccion = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbMunicipio = new javax.swing.JComboBox();
        cbLocalidad = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        tfCalle = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lupaCalle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTipoVia = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        tfLetra = new javax.swing.JTextField();
        tfEscalera = new javax.swing.JTextField();
        tfMano = new javax.swing.JTextField();
        tfCp = new javax.swing.JTextField();
        tfTfn1 = new javax.swing.JTextField();
        tfTfn2 = new javax.swing.JTextField();
        tfTfn3 = new javax.swing.JTextField();
        tfTfn4 = new javax.swing.JTextField();
        tfPiso = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        pOtrosDatos = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        rbProv = new javax.swing.JRadioButton();
        rbOtraProv = new javax.swing.JRadioButton();
        tfProvinciaCentro = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        rbA = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        rbD = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        cbDiscapacidad = new javax.swing.JComboBox();
        lupaCentro = new javax.swing.JLabel();
        bBorrar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1300, 720));
        setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("SOLICITUD INSCRIPCIÓN");

        pTutor.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DEL PADRE/MADRE O TUTOR/A"));

        jLabel3.setText("* DNI");

        jLabel4.setText("* Nombre");

        jLabel5.setText("* Primer Apellido");

        tfApel1Tutor.setToolTipText("");

        jLabel6.setText("* SegundoApellido");

        tfApel2Tutor.setToolTipText("");

        tfDniTutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDniTutorFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pTutorLayout = new javax.swing.GroupLayout(pTutor);
        pTutor.setLayout(pTutorLayout);
        pTutorLayout.setHorizontalGroup(
            pTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTutorLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pTutorLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfApel2Tutor))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pTutorLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(tfApel1Tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pTutorLayout.createSequentialGroup()
                        .addGroup(pTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(pTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombreTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDniTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTutorLayout.setVerticalGroup(
            pTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTutorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDniTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNombreTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfApel1Tutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfApel2Tutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pMenor.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DEL PARTICIPANTE"));

        jLabel9.setText(" DNI");

        jLabel10.setText("* Nombre");

        jLabel11.setText("* Primer Apellido");

        tfApel1Menor.setToolTipText("");

        jLabel7.setText("* SegundoApellido");

        tfApel2Menor.setToolTipText("");

        jLabel12.setText("* Sexo");

        grupoSexo.add(rbMasculino);
        rbMasculino.setText("Masculino");

        grupoSexo.add(rbMujer);
        rbMujer.setText("Femenino");

        jLabel13.setText("* Fecha de nacimiento");

        jLabel14.setText("(dd/mm/aaaa)");

        tfDniMenor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDniMenorFocusGained(evt);
            }
        });

        tfFechaNacMenor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFechaNacMenorFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pMenorLayout = new javax.swing.GroupLayout(pMenor);
        pMenor.setLayout(pMenorLayout);
        pMenorLayout.setHorizontalGroup(
            pMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenorLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenorLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfApel2Menor))
                    .addGroup(pMenorLayout.createSequentialGroup()
                        .addGroup(pMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pMenorLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfDniMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNombreMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pMenorLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(19, 19, 19)
                                    .addComponent(tfApel1Menor))
                                .addGroup(pMenorLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfFechaNacMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pMenorLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbMasculino)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbMujer))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pMenorLayout.setVerticalGroup(
            pMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(tfNombreMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDniMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApel1Menor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfApel2Menor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(pMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMasculino)
                    .addComponent(jLabel12)
                    .addComponent(rbMujer))
                .addGap(24, 24, 24)
                .addGroup(pMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(tfFechaNacMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        pDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder("DIRECCIÓN"));

        jLabel16.setText("* Municipio");

        jLabel17.setText("* Localidad");

        jLabel18.setText("*Código Postal");

        cbMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMunicipioActionPerformed(evt);
            }
        });

        cbLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocalidadActionPerformed(evt);
            }
        });

        jLabel19.setText("* Nombre");

        jLabel20.setText("Número");

        jLabel21.setText("Letra");

        jLabel22.setText("Piso");

        jLabel24.setText("Escalera");

        jLabel25.setText("Mano");

        jLabel26.setText("*Teléfonos");

        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Indique el teléfono de localización durante la estancia en la colonia, marcando la casilla al lado del teléfono.");

        lupaCalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        lupaCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaCalleMouseClicked(evt);
            }
        });

        jLabel2.setText("* Tipo de via");

        tfNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNumeroFocusGained(evt);
            }
        });

        tfLetra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfLetraFocusGained(evt);
            }
        });

        tfEscalera.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEscaleraFocusGained(evt);
            }
        });

        tfCp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCpFocusGained(evt);
            }
        });

        tfTfn1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTfn1FocusGained(evt);
            }
        });

        tfTfn2.setEnabled(false);
        tfTfn2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTfn2FocusGained(evt);
            }
        });

        tfTfn3.setEnabled(false);
        tfTfn3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTfn3FocusGained(evt);
            }
        });

        tfTfn4.setEnabled(false);

        tfPiso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPisoFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pDireccionLayout = new javax.swing.GroupLayout(pDireccion);
        pDireccion.setLayout(pDireccionLayout);
        pDireccionLayout.setHorizontalGroup(
            pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDireccionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDireccionLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDireccionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                                .addComponent(jLabel23)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pDireccionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfEscalera, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMano, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pDireccionLayout.createSequentialGroup()
                        .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDireccionLayout.createSequentialGroup()
                                .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pDireccionLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pDireccionLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCp, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDireccionLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTipoVia, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lupaCalle))
                            .addGroup(pDireccionLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(26, 26, 26)
                                .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTfn3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(tfTfn1))
                                .addGap(10, 10, 10)
                                .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTfn2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTfn4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(23, Short.MAX_VALUE))))
            .addGroup(pDireccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pDireccionLayout.setVerticalGroup(
            pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDireccionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lupaCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(tfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(tfTipoVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDireccionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(41, 41, 41))
                    .addGroup(pDireccionLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEscalera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(tfTfn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTfn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTfn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTfn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pOtrosDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("OTROS DATOS"));

        jLabel29.setText("* Centro de enseñanza");

        grupoProvincia.add(rbProv);
        rbProv.setSelected(true);
        rbProv.setText("Alava");
        rbProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbProvActionPerformed(evt);
            }
        });

        grupoProvincia.add(rbOtraProv);
        rbOtraProv.setText("Otra");
        rbOtraProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOtraProvActionPerformed(evt);
            }
        });

        jLabel30.setText("* Modelo");

        grupoModelo.add(rbA);
        rbA.setText("A");

        grupoModelo.add(rbB);
        rbB.setText("B");

        grupoModelo.add(rbD);
        rbD.setText("D");

        jLabel32.setText("* Discapacidad");

        cbDiscapacidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));

        lupaCentro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        lupaCentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaCentroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pOtrosDatosLayout = new javax.swing.GroupLayout(pOtrosDatos);
        pOtrosDatos.setLayout(pOtrosDatosLayout);
        pOtrosDatosLayout.setHorizontalGroup(
            pOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOtrosDatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pOtrosDatosLayout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbProv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbOtraProv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfProvinciaCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lupaCentro)
                        .addGap(69, 69, 69))
                    .addGroup(pOtrosDatosLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pOtrosDatosLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(36, 36, 36)
                        .addComponent(rbA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbD)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pOtrosDatosLayout.setVerticalGroup(
            pOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOtrosDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(rbProv)
                        .addComponent(rbOtraProv)
                        .addComponent(tfProvinciaCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lupaCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(rbA)
                    .addComponent(rbB)
                    .addComponent(rbD))
                .addGap(18, 18, 18)
                .addGroup(pOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cbDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pTutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(bGuardar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pOtrosDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bBorrar)
                                .addGap(121, 121, 121)
                                .addComponent(bCancelar)
                                .addGap(296, 296, 296)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pOtrosDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(pMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBorrar)
                    .addComponent(bGuardar)
                    .addComponent(bCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents
    // DATOS INICIALES
    private void datosIniciales() {
        // Las lupas quedan desactivadas hasta haber elegido la localidad.
        tfTipoVia.setEditable(false);tfCalle.setEditable(false); lupaCalle.setEnabled(false);
        tfProvinciaCentro.setEditable(false); lupaCentro.setEnabled(false);
        // Los modelos educativos quedan desactivados hasta haber elegido el centro.
        rbA.setEnabled(false);rbB.setEnabled(false);rbD.setEnabled(false);
        // Provincia
        switch (prov){
            case "ARB":
                rbProv.setText("Araba");
                break;
            case "BZK":
                rbProv.setText("Bizkaia");
                break;
            case "GZK":
                rbProv.setText("Gipuzkoa");
                break;
        }
        // Municipios
        // Vaciamos lista desplegable de municipios.
        cbMunicipio.removeAllItems();
        municipios=Main.findMunByProv();//Main.getMunicipios();
        // Llenar lista desplegable de municipios.
        for(int x=0;x<municipios.size();x++)
        {
            cbMunicipio.insertItemAt(municipios.get(x).getNombremunic(), x);
        }

    }
    
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        borrarFormulario();
        Main.cancelarPanel();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        try{
            verificarDatos();
            construirObjetos();
            if(Main.controlInscripciones()==false)
            {
                mostrar("La solicitud tienes las tres plazas ocupadas.\nSi desea registrar esta inscripción debe abrir una nueva solicitud.");
                Main.cancelarPanel();
            }                      
            //borrarFormulario();
        }
        catch(TfnIncorrecto ex){mostrar(ex.getMensaje());}
        catch(ExEnteros ex){mostrar(ex.getMensaje());}
        catch(CampoVacio ex){mostrar(ex.getMensaje());}
        catch(ExGenerica ex){mostrar(ex.getMessage());}
        catch(Exception ex){
            System.out.println(ex.getMessage());
            mostrar("Ha sido imposible registrar la inscripción");
        }
    }//GEN-LAST:event_bGuardarActionPerformed
    
    // LUPAS
    private void lupaCalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaCalleMouseClicked
       Main.buildLupa("calles","",locIndex);
    }//GEN-LAST:event_lupaCalleMouseClicked
    
    public void rellenarTfCalle(Via via) {
        tfTipoVia.setText(via.getTipovia());
        tfCalle.setText(via.getNombrevia());
    }

    private void lupaCentroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaCentroMouseClicked
        String prov;
        if(rbProv.isSelected())
            prov="seleccionada";
        else
            prov="otra";
        Main.buildLupa("centros",prov,cbLocalidad.getSelectedIndex());
    }//GEN-LAST:event_lupaCentroMouseClicked
    
    public void rellenarTfCentro(Centro centro) {
        tfProvinciaCentro.setText(centro.getNombrecent());
        ArrayList<Modelo> modelos=Main.findModByCent(centro.getIdcentro().toString());
        // Desactivamos todo, antes de activar los que interesa.
        rbA.setEnabled(false);rbB.setEnabled(false);rbD.setEnabled(false);
        // Adecuamos las opciones de modelo educativo que tiene el centro a las del formulario.
        for(int x=0;x<modelos.size();x++)
        {
            String st=modelos.get(x).getIdmodelo();
            if(st.equalsIgnoreCase("A"))
                rbA.setEnabled(true);
            else
                if(st.equalsIgnoreCase("B"))
                    rbB.setEnabled(true);
                else
                    rbD.setEnabled(true);
        }
    }
    
    // COMBO BOXES
    private void cbMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMunicipioActionPerformed
        // Borramos los datos del formulario que dependen del municipio.
        cbLocalidad.removeAllItems();tfTipoVia.setText(null);tfCalle.setText(null);
        
        if(cbMunicipio.getSelectedIndex()!= -1)
        {
            // Tanto la combo box de los municipios como el array de municipios es coincidente.
            munIndex = cbMunicipio.getSelectedIndex();
            // Vaciamos lista desplegable de municipios.
            localidades=Main.findLocByMun(municipios.get(munIndex).getIdmunicipio().toString());            
            // Llenar lista desplegable de municipios.
            for(int x=0;x<localidades.size();x++)
            {
                cbLocalidad.insertItemAt(localidades.get(x).getNombreloc(), x);
            }     
        }
    }//GEN-LAST:event_cbMunicipioActionPerformed

    private void cbLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocalidadActionPerformed
        if(cbLocalidad.getSelectedIndex()!= -1)
        {
            locIndex = cbLocalidad.getSelectedIndex();       
            // Activamos las lupas.
            lupaCalle.setEnabled(true); lupaCentro.setEnabled(true);
        }
        
    }//GEN-LAST:event_cbLocalidadActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        borrarFormulario();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void tfNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNumeroFocusGained
        quitarRojoTextField(tfNumero);
    }//GEN-LAST:event_tfNumeroFocusGained

    private void tfLetraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLetraFocusGained
        quitarRojoTextField(tfLetra);
    }//GEN-LAST:event_tfLetraFocusGained

    private void tfEscaleraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEscaleraFocusGained
        quitarRojoTextField(tfEscalera);
    }//GEN-LAST:event_tfEscaleraFocusGained

    private void rbProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbProvActionPerformed
        tfProvinciaCentro.setText(null);
    }//GEN-LAST:event_rbProvActionPerformed

    private void rbOtraProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOtraProvActionPerformed
        tfProvinciaCentro.setText(null);
    }//GEN-LAST:event_rbOtraProvActionPerformed

    private void tfDniTutorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDniTutorFocusGained
        quitarRojoTextField(tfDniTutor);
    }//GEN-LAST:event_tfDniTutorFocusGained

    private void tfDniMenorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDniMenorFocusGained
        quitarRojoTextField(tfDniMenor);
    }//GEN-LAST:event_tfDniMenorFocusGained

    private void tfCpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCpFocusGained
        quitarRojoTextField(tfCp);
    }//GEN-LAST:event_tfCpFocusGained

    private void tfFechaNacMenorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFechaNacMenorFocusGained
        quitarRojoTextField(tfFechaNacMenor);
    }//GEN-LAST:event_tfFechaNacMenorFocusGained

    private void tfTfn1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTfn1FocusGained
        quitarRojoTextField(tfTfn1);
        tfTfn2.setEnabled(true);
    }//GEN-LAST:event_tfTfn1FocusGained

    private void tfTfn2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTfn2FocusGained
        quitarRojoTextField(tfTfn2);
        tfTfn3.setEnabled(true);
    }//GEN-LAST:event_tfTfn2FocusGained

    private void tfTfn3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTfn3FocusGained
        quitarRojoTextField(tfTfn3);
        tfTfn4.setEnabled(true);
    }//GEN-LAST:event_tfTfn3FocusGained

    private void tfPisoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPisoFocusGained
        quitarRojoTextField(tfPiso);
    }//GEN-LAST:event_tfPisoFocusGained

    // VERIFICACIONES
    private void verificarDatos() throws Exception{
        // Campos obligatorios de "Datos del padre/madre o tutor/a".
        if(tfDniTutor.getText().isEmpty()||tfNombreTutor.getText().isEmpty()||tfApel1Tutor.getText().isEmpty()||tfApel2Tutor.getText().isEmpty())
        {
            throw new CampoVacio();            
        }
        // Campos obligatorios de "Datos del menor".
        if(tfNombreMenor.getText().isEmpty()||tfApel1Menor.getText().isEmpty()||tfApel2Menor.getText().isEmpty()||
                grupoSexo.getSelection()==null||tfFechaNacMenor.getText().isEmpty())
        {
            throw new CampoVacio();            
        }
        // Campos obligatorios de "Dirección".
        if(cbMunicipio.getSelectedItem()==null||cbLocalidad.getSelectedItem()==null||tfCp.getText().isEmpty()||tfTipoVia.getText().isEmpty()||
                tfCalle.getText().isEmpty()||tfTfn1.getText().isEmpty())
        {
            throw new CampoVacio();            
        }
        // Campos obligatorios de "Otros Datos"
        if(tfProvinciaCentro.getText().isEmpty()||grupoModelo.getSelection()==null)
        {
            throw new CampoVacio();
        }

        // DNI del tutor
        if(verificarDni(tfDniTutor.getText().toUpperCase())==false)
        {
            ponerRojoTextField(tfDniTutor);
            throw new ExGenerica("El DNI del padre/madre o tutor/a no es correcto.");
        }
        // DNI del menor.
            // El dni del menor no es obligatorio.
        if(tfDniMenor.getText().isEmpty()==false)
        {
            if(verificarDni(tfDniMenor.getText().toUpperCase())==false)
            {
                ponerRojoTextField(tfDniMenor);
                throw new ExGenerica("El DNI del menor no es correcto.");
            }      
        }
        // Fecha de nacimiento del menor. Tiene que tener entre 7 y 13 años y cumplir con el patrón.
        if(verificarFechaNacMenor(tfFechaNacMenor.getText())==false)
        {
            ponerRojoTextField(tfFechaNacMenor);
            throw new ExGenerica("El menor debe tener entre 7 y 13 años. Revise el campo fecha de nacimiento.");
        }
        // Código postal.
        if(stringToInteger(tfCp.getText())==false||tfCp.getText().length()>5)
        {
            ponerRojoTextField(tfCp);
                throw new ExGenerica("El código postal no es correcto");
        }
        // Teléfono obligatorio. Suponemos que los teléfonos son todos de 9 dígitos.
        if(stringToInteger(tfTfn1.getText())==false||tfTfn1.getText().length()>9)
        {
            ponerRojoTextField(tfTfn1);
                throw new TfnIncorrecto();
        }
        
        // Campos NO obligatorios de la dirección. Controlando excepciones de conversión para los enteros
        // Numero
        if(tfNumero.getText().isEmpty()==false&&stringToInteger(tfNumero.getText())==false)
        {
            ponerRojoTextField(tfNumero);
                throw new ExEnteros();   
        }
        // Letra
        if(tfLetra.getText().isEmpty()==false&&tfLetra.getText().length()>1)
        {
            ponerRojoTextField(tfLetra);
            throw new ExGenerica("Sólo se admite una letra.");
        }
        // Piso
        if(tfPiso.getText().isEmpty()==false&&stringToInteger(tfPiso.getText())==false)
        {
            ponerRojoTextField(tfPiso);
                throw new ExEnteros();   
        }
        
        // El campo 'Escalera' y 'Mano' lo dejamos sin verificar por la variedad de opciones.
        // Teléfonos secundarios.
        if(tfTfn2.getText().isEmpty()==false&&(stringToInteger(tfTfn2.getText())==false||tfTfn2.getText().length()>9))
        {
            ponerRojoTextField(tfTfn2);
                throw new TfnIncorrecto();
        }
        if(tfTfn3.getText().isEmpty()==false&&(stringToInteger(tfTfn3.getText())==false||tfTfn3.getText().length()>9))
        {
            ponerRojoTextField(tfTfn3);
                throw new TfnIncorrecto();
        }
        if(tfTfn4.getText().isEmpty()==false&&(stringToInteger(tfTfn4.getText())==false||tfTfn4.getText().length()>9))
        {
            ponerRojoTextField(tfTfn4);
                throw new TfnIncorrecto();
        }
    }
    
    private boolean verificarDni(String dni) throws Exception{
        // Patrón
        Pattern pat=Pattern.compile("[0-9]{8}[a-zA-Z]");
        Matcher mat=pat.matcher(dni);
        if(mat.matches()==false)
            return false;
        // Letra del DNI.
        String caracteres="TRWAGMYFPDXBNJZSQVHLCKE";
        String dniNumeros=dni.substring(0,8);
        int modulo=Integer.parseInt(dniNumeros) % 23;
        char letra=caracteres.charAt(modulo);
        char letraDni=dni.charAt(8);
        if(letra!=letraDni)
            return false;
        // Dni válido
        return true;
    }
        
    private boolean verificarFechaNacMenor(String fechaString) {
        // Controlamos que sea un formato válido con la excepción que se genera si no lo es.
        try {
            Calendar actual=Calendar.getInstance();
            Calendar fechaNac=Calendar.getInstance();
            Calendar x=new GregorianCalendar();
            SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            fechaNac.setTime(sdf.parse(fechaString));
            
            // Si mayor de 13 años.
            x.setTime(sdf.parse(fechaString));
            x.add(Calendar.YEAR, 13);
            if(x.before(actual))
                return false;
            
            // Si menor de 7 años.
            x.setTime(sdf.parse(fechaString));
            x.add(Calendar.YEAR, 7);
            if(x.after(actual))
                return false;
            
            // Fecha dentro de los valores.
            return true;
        } catch (ParseException ex) {
            return false;
        }
    }
    
    private boolean stringToInteger(String text) {
        try{
            int numero=Integer.parseInt(text);
        }
        catch(Exception ex){return false;}
        return true;
    }

    private void ponerRojoTextField(JTextField textField) {
        textField.setBackground(Color.red);
    }

    private void quitarRojoTextField(JTextField textField) {
        textField.setBackground(Color.WHITE);
    }
    
    // CONSTRUCCION DE OBJETOS
    private ArrayList makeArrayTfn() {
        ArrayList<String> telefonos=new ArrayList();
        telefonos.add(tfTfn1.getText());
        if(tfTfn2.getText().isEmpty()==false)
            telefonos.add(tfTfn2.getText());
        if(tfTfn3.getText().isEmpty()==false)
            telefonos.add(tfTfn3.getText());
        if(tfTfn4.getText().isEmpty()==false)
            telefonos.add(tfTfn4.getText());
        return telefonos;
    }

    private void construirObjetos() throws Exception{
        // Datos Direccion
        Main.constDireccion(tfCp.getText(),tfNumero.getText(),tfLetra.getText(),tfPiso.getText(),tfEscalera.getText(),tfMano.getText());
        
        // Datos tutor
        ArrayList<String> telefonos = makeArrayTfn();
        Main.constTutor(tfDniTutor.getText(),tfNombreTutor.getText(),tfApel1Tutor.getText(),tfApel2Tutor.getText(),telefonos);
        
        // Datos Menor
        //RadioButtons
        String sexo=""; String modelo="";
        if(rbMasculino.isSelected())
            sexo="M";
        else
            sexo="F";
        if(rbA.isSelected())
            modelo="A";
        else
            if(rbB.isSelected())
                modelo="B";
            else
                modelo="D";
        
        Main.constMenor(tfDniMenor.getText(),tfNombreMenor.getText(),tfApel1Menor.getText(),tfApel2Menor.getText(),sexo,tfFechaNacMenor.getText(),cbDiscapacidad.getSelectedItem().toString(),modelo);
        
        

    }
    
    // OTROS
    private void borrarFormulario() {
        // Borrar datos del padre/madre o tutor/a.
        tfDniTutor.setText(null);tfNombreTutor.setText(null);tfApel1Tutor.setText(null);tfApel2Tutor.setText(null);
        // Borrar datos del menor.
        tfDniMenor.setText(null);tfNombreMenor.setText(null);tfApel1Menor.setText(null);tfApel2Menor.setText(null);
        grupoSexo.clearSelection();tfFechaNacMenor.setText(null);cbDiscapacidad.setSelectedIndex(0);
        // Borrar datos de la dirección.
        cbLocalidad.removeAllItems();tfCp.setText(null);
        tfTipoVia.setText(null);tfCalle.setText(null);tfPiso.setText(null);tfNumero.setText(null);tfLetra.setText(null);
        tfPiso.setText(null);tfEscalera.setText(null);tfMano.setText(null);
        tfTfn1.setText(null);tfTfn2.setText(null);tfTfn3.setText(null);tfTfn4.setText(null);
        // Borrar otros datos.
        grupoProvincia.clearSelection();tfProvinciaCentro.setText(null);grupoModelo.clearSelection();cbDiscapacidad.setSelectedIndex(0);
        // Set telefonos enabled(false).
        tfTfn2.setEnabled(false);tfTfn3.setEnabled(false);tfTfn4.setEnabled(false);
        // Set modelos enabled(false).
        rbA.setEnabled(false);rbB.setEnabled(false);rbD.setEnabled(false);
        // Deseleccionar municipio.
        cbMunicipio.setSelectedIndex(-1);
    }
    
    private void mostrar(String text){
        JOptionPane.showMessageDialog(null, text);
    }
    
    private void soloGuardarCancelar() {
        // Desactivamos todo para que solo pueda guardarse o cancelarse la solicitud.
        bBorrar.setEnabled(false);
        pTutor.setEnabled(false);pMenor.setEnabled(false);pDireccion.setEnabled(false);pOtrosDatos.setEnabled(false);
    }   

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JComboBox cbDiscapacidad;
    private javax.swing.JComboBox cbLocalidad;
    private javax.swing.JComboBox cbMunicipio;
    private javax.swing.ButtonGroup grupoModelo;
    private javax.swing.ButtonGroup grupoProvincia;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lupaCalle;
    private javax.swing.JLabel lupaCentro;
    private javax.swing.JPanel pDireccion;
    private javax.swing.JPanel pMenor;
    private javax.swing.JPanel pOtrosDatos;
    private javax.swing.JPanel pTutor;
    private javax.swing.JRadioButton rbA;
    private javax.swing.JRadioButton rbB;
    private javax.swing.JRadioButton rbD;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JRadioButton rbOtraProv;
    private javax.swing.JRadioButton rbProv;
    private javax.swing.JTextField tfApel1Menor;
    private javax.swing.JTextField tfApel1Tutor;
    private javax.swing.JTextField tfApel2Menor;
    private javax.swing.JTextField tfApel2Tutor;
    private javax.swing.JTextField tfCalle;
    private javax.swing.JTextField tfCp;
    private javax.swing.JTextField tfDniMenor;
    private javax.swing.JTextField tfDniTutor;
    private javax.swing.JTextField tfEscalera;
    private javax.swing.JTextField tfFechaNacMenor;
    private javax.swing.JTextField tfLetra;
    private javax.swing.JTextField tfMano;
    private javax.swing.JTextField tfNombreMenor;
    private javax.swing.JTextField tfNombreTutor;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfPiso;
    private javax.swing.JTextField tfProvinciaCentro;
    private javax.swing.JTextField tfTfn1;
    private javax.swing.JTextField tfTfn2;
    private javax.swing.JTextField tfTfn3;
    private javax.swing.JTextField tfTfn4;
    private javax.swing.JTextField tfTipoVia;
    // End of variables declaration//GEN-END:variables



}
