/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Modelo.UML.Centro;
import Modelo.UML.Localidad;
import Modelo.UML.Via;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import proyectoudaleku.Main;

/**
 *
 * @author 1gprog07
 */
public class PanLupa extends javax.swing.JFrame {
    private ArrayList<Localidad> localidades;

    /**
     * Creates new form panelLupa
     */
    public PanLupa() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public PanLupa(String tipo, String text, String parametro) {
        initComponents();
        setLocationRelativeTo(null);
        lTitulo.setText(tipo.toUpperCase()); 
        //lProv.setText(text.toUpperCase());
        switch(tipo){
            case "calles":
                DefaultListModel modeloCalles = new DefaultListModel();
                ArrayList<Via> vias= Main.findViasByLoc(parametro);
                for(int x=0;x<vias.size();x++)
                {
                    modeloCalles.add(x, vias.get(x).getNombrevia());
                }
                list.setModel(modeloCalles);
                break;
                
            case "centros":
                DefaultListModel modeloCentros = new DefaultListModel();
                // Si queremos los centros de la misma provincia.
                ArrayList<Centro> centros=Main.findCentByProv(parametro,text);
                                    
                for(int x=0;x<centros.size();x++)
                {
                    modeloCentros.add(x, centros.get(x).getNombrecent());
                }
                list.setModel(modeloCentros);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        lTitulo = new javax.swing.JLabel();
        lProv = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        lDe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(list);

        lTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lTitulo.setText("CALLES");

        lProv.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lProv.setText("ARABA");

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        lDe.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lDe.setText("DE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(lTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lProv))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(bAceptar)
                        .addGap(224, 224, 224)
                        .addComponent(bCancelar)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitulo)
                    .addComponent(lProv)
                    .addComponent(lDe))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        Main.cancelarLupa();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        switch (lTitulo.getText()){
            case "CALLES":
        {
            try {
                // El ArrayList de municipios del Main es coincidente con esta lista. Así sabemos qué municipio seleccionamos.
                Main.sendViaToInscripcion(list.getSelectedIndex());
            } catch (SQLException ex) {
                Logger.getLogger(PanLupa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;
            case "CENTROS":
                // El ArrayList de centros del Main es coincidente con esta lista. Así sabemos qué municipio seleccionamos.
                Main.sendCentroToInscripcion(list.getSelectedIndex());
                break;
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanLupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanLupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanLupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanLupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanLupa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lDe;
    private javax.swing.JLabel lProv;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JList list;
    // End of variables declaration//GEN-END:variables
}
